name: Atualizar calendário F1 2026

on:
  schedule:
    # roda toda segunda-feira às 06:00 UTC
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Atualizar timestamp do calendário
        run: |
          sed -i "s/LAST-MODIFIED:.*/LAST-MODIFIED:$(date -u +'%Y%m%dT%H%M%SZ')/" f1_2026_brt.ics || true

      - name: Commit e push se houver mudanças
        run: |
          git add f1_2026_brt.ics
          git diff --cached --quiet || git commit -m "Atualiza calendário F1 2026 automaticamente"
          git push
